In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data_for_ml.csv")

In [3]:
df

,Hours_Studied,Sleep_Hours,Internet_Usage,Gender,Study_Method,Attendance,Final_Score
0,2.0,6.0,3.0,Male,Self Study,75.0,55.0
1,3.0,7.0,2.0,Female,Coaching,80.0,60.0
2,4.0,6.0,4.0,male,Self study,78.0,62.0
3,5.0,8.0,3.0,Femle,Group Study,85.0,70.0
4,6.0,7.0,5.0,Male,Self Study,88.0,72.0
5,7.0,6.0,6.0,Female,coaching,90.0,75.0
6,8.0,7.0,4.0,Male,Group study,92.0,80.0
7,2.0,5.0,7.0,Female,Self Study,70.0,50.0
8,3.0,6.0,6.0,Male,Self Study,75.0,55.0
9,4.0,7.0,5.0,Female,Group Study,82.0,65.0
10,5.0,8.0,4.0,Male,Self Study,85.0,68.0
11,6.0,6.0,5.0,Female,Coaching,88.0,72.0
12,7.0,7.0,6.0,Male,Self study,90.0,76.0
13,8.0,8.0,3.0,Female,Group Study,95.0,85.0
14,NaN,7.0,4.0,Male,Self Study,80.0,65.0
15,5.0,NaN,5.0,Female,Coaching,85.0,70.0
16,6.0,6.0,NaN,Male,Group Study,88.0,72.0
17,7.0,7.0,6.0,NaN,Self Study,90.0,75.0
18,8.0,8.0,3.0,Female,NaN,92.0,80.0
19,4.0,6.0,5.0,Male,Self Study,NaN,60.0
20,3.0,5.0,6.0,Female,Coaching,78.0,NaN
21,2.0,6.0,7.0,Male,Self Study,70.0,52.0
22,5.0,8.0,4.0,Female,Group Study,85.0,68.0
23,6.0,7.0,5.0,Male,Self Study,88.0,72.0
24,7.0,6.0,6.0,Female,Coaching,90.0,75.0
25,8.0,7.0,4.0,Male,Group Study,92.0,80.0
26,2.0,5.0,7.0,Female,Self Study,70.0,50.0
27,3.0,6.0,6.0,Male,Self Study,75.0,55.0
28,4.0,7.0,5.0,Female,Group Study,82.0,65.0
29,5.0,8.0,4.0,Male,Self Study,85.0,68.0
30,6.0,6.0,5.0,Female,Coaching,88.0,72.0
31,7.0,7.0,6.0,Male,Self Study,90.0,76.0
32,8.0,8.0,3.0,Female,Group Study,95.0,85.0
33,2.0,6.0,3.0,Male,Self Study,75.0,55.0
34,3.0,7.0,2.0,Female,Coaching,80.0,60.0
35,4.0,6.0,4.0,male,Self study,78.0,62.0
36,5.0,8.0,3.0,Femle,Group Study,85.0,70.0
37,6.0,7.0,5.0,Male,Self Study,88.0,72.0
38,7.0,6.0,6.0,Female,coaching,90.0,75.0
39,8.0,7.0,4.0,Male,Group study,92.0,80.0
40,2.0,5.0,7.0,Female,Self Study,70.0,50.0
41,3.0,6.0,6.0,Male,Self Study,75.0,55.0
42,4.0,7.0,5.0,Female,Group Study,82.0,65.0
43,5.0,8.0,4.0,Male,Self Study,85.0,68.0
44,6.0,6.0,5.0,Female,Coaching,88.0,72.0
45,7.0,7.0,6.0,Male,Self study,90.0,76.0
46,8.0,8.0,3.0,Female,Group Study,95.0,85.0
47,1.0,5.0,8.0,Male,Self Study,65.0,45.0
48,9.0,8.0,2.0,Female,Coaching,96.0,88.0
49,10.0,7.0,1.0,Male,Self Study,98.0,92.0
50,1.0,4.0,9.0,Female,Group Study,60.0,40.0
51,9.0,9.0,2.0,Male,Self Study,97.0,90.0
52,10.0,8.0,1.0,Female,Coaching,99.0,94.0
53,3.0,6.0,6.0,Male,Self Study,75.0,55.0
54,3.0,6.0,6.0,Male,Self Study,75.0,55.0
55,4.0,7.0,5.0,Female,Group Study,82.0,65.0
56,4.0,7.0,5.0,Female,Group Study,82.0,65.0

In [4]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [5]:
df.isna().sum()

Hours_Studied     1
Sleep_Hours       1
Internet_Usage    1
Gender            1
Study_Method      1
Attendance        1
Final_Score       1
dtype: int64

In [6]:
df["Hours_Studied"] = df["Hours_Studied"].fillna(df["Hours_Studied"].median())

In [7]:
df["Sleep_Hours"] = df["Sleep_Hours"].fillna(df["Sleep_Hours"].median())

In [8]:
df["Internet_Usage"] = df["Internet_Usage"].fillna(df["Internet_Usage"].median())

In [9]:
df["Gender"] = df["Gender"].fillna(df['Gender'].mode()[0])

In [10]:
df["Study_Method"] = df["Study_Method"].fillna(df['Study_Method'].mode()[0])

In [11]:
df["Attendance"] = df["Attendance"].fillna(df["Attendance"].median())

In [12]:
df["Final_Score"] = df["Final_Score"].fillna(df["Final_Score"].median())

In [13]:
df.isna().sum()

Hours_Studied     0
Sleep_Hours       0
Internet_Usage    0
Gender            0
Study_Method      0
Attendance        0
Final_Score       0
dtype: int64

In [14]:
df.dtypes

Hours_Studied     float64
Sleep_Hours       float64
Internet_Usage    float64
Gender             object
Study_Method       object
Attendance        float64
Final_Score       float64
dtype: object

In [15]:
df[['Hours_Studied','Sleep_Hours','Internet_Usage','Attendance','Final_Score']] = df[['Hours_Studied','Sleep_Hours','Internet_Usage','Attendance','Final_Score']].astype(int)

In [16]:
df

,Hours_Studied,Sleep_Hours,Internet_Usage,Gender,Study_Method,Attendance,Final_Score
0,2,6,3,Male,Self Study,75,55
1,3,7,2,Female,Coaching,80,60
2,4,6,4,male,Self study,78,62
3,5,8,3,Femle,Group Study,85,70
4,6,7,5,Male,Self Study,88,72
5,7,6,6,Female,coaching,90,75
6,8,7,4,Male,Group study,92,80
7,2,5,7,Female,Self Study,70,50
8,3,6,6,Male,Self Study,75,55
9,4,7,5,Female,Group Study,82,65
10,5,8,4,Male,Self Study,85,68
11,6,6,5,Female,Coaching,88,72
12,7,7,6,Male,Self study,90,76
13,8,8,3,Female,Group Study,95,85
14,5,7,4,Male,Self Study,80,65
15,5,7,5,Female,Coaching,85,70
16,6,6,5,Male,Group Study,88,72
17,7,7,6,Female,Self Study,90,75
18,8,8,3,Female,Self Study,92,80
19,4,6,5,Male,Self Study,85,60
20,3,5,6,Female,Coaching,78,69
21,2,6,7,Male,Self Study,70,52
22,5,8,4,Female,Group Study,85,68
23,6,7,5,Male,Self Study,88,72
24,7,6,6,Female,Coaching,90,75
25,8,7,4,Male,Group Study,92,80
26,2,5,7,Female,Self Study,70,50
27,3,6,6,Male,Self Study,75,55
28,4,7,5,Female,Group Study,82,65
29,5,8,4,Male,Self Study,85,68
30,6,6,5,Female,Coaching,88,72
31,7,7,6,Male,Self Study,90,76
32,8,8,3,Female,Group Study,95,85
33,2,6,3,Male,Self Study,75,55
34,3,7,2,Female,Coaching,80,60
35,4,6,4,male,Self study,78,62
36,5,8,3,Femle,Group Study,85,70
37,6,7,5,Male,Self Study,88,72
38,7,6,6,Female,coaching,90,75
39,8,7,4,Male,Group study,92,80
40,2,5,7,Female,Self Study,70,50
41,3,6,6,Male,Self Study,75,55
42,4,7,5,Female,Group Study,82,65
43,5,8,4,Male,Self Study,85,68
44,6,6,5,Female,Coaching,88,72
45,7,7,6,Male,Self study,90,76
46,8,8,3,Female,Group Study,95,85
47,1,5,8,Male,Self Study,65,45
48,9,8,2,Female,Coaching,96,88
49,10,7,1,Male,Self Study,98,92
50,1,4,9,Female,Group Study,60,40
51,9,9,2,Male,Self Study,97,90
52,10,8,1,Female,Coaching,99,94
53,3,6,6,Male,Self Study,75,55
54,3,6,6,Male,Self Study,75,55
55,4,7,5,Female,Group Study,82,65
56,4,7,5,Female,Group Study,82,65

In [17]:
df[df.duplicated()]

,Hours_Studied,Sleep_Hours,Internet_Usage,Gender,Study_Method,Attendance,Final_Score
23,6,7,5,Male,Self Study,88,72
26,2,5,7,Female,Self Study,70,50
27,3,6,6,Male,Self Study,75,55
28,4,7,5,Female,Group Study,82,65
29,5,8,4,Male,Self Study,85,68
30,6,6,5,Female,Coaching,88,72
32,8,8,3,Female,Group Study,95,85
33,2,6,3,Male,Self Study,75,55
34,3,7,2,Female,Coaching,80,60
35,4,6,4,male,Self study,78,62
36,5,8,3,Femle,Group Study,85,70
37,6,7,5,Male,Self Study,88,72
38,7,6,6,Female,coaching,90,75
39,8,7,4,Male,Group study,92,80
40,2,5,7,Female,Self Study,70,50
41,3,6,6,Male,Self Study,75,55
42,4,7,5,Female,Group Study,82,65
43,5,8,4,Male,Self Study,85,68
44,6,6,5,Female,Coaching,88,72
45,7,7,6,Male,Self study,90,76
46,8,8,3,Female,Group Study,95,85
53,3,6,6,Male,Self Study,75,55
54,3,6,6,Male,Self Study,75,55
55,4,7,5,Female,Group Study,82,65
56,4,7,5,Female,Group Study,82,65

In [18]:
df = df.drop_duplicates()

In [19]:
df

,Hours_Studied,Sleep_Hours,Internet_Usage,Gender,Study_Method,Attendance,Final_Score
0,2,6,3,Male,Self Study,75,55
1,3,7,2,Female,Coaching,80,60
2,4,6,4,male,Self study,78,62
3,5,8,3,Femle,Group Study,85,70
4,6,7,5,Male,Self Study,88,72
5,7,6,6,Female,coaching,90,75
6,8,7,4,Male,Group study,92,80
7,2,5,7,Female,Self Study,70,50
8,3,6,6,Male,Self Study,75,55
9,4,7,5,Female,Group Study,82,65
10,5,8,4,Male,Self Study,85,68
11,6,6,5,Female,Coaching,88,72
12,7,7,6,Male,Self study,90,76
13,8,8,3,Female,Group Study,95,85
14,5,7,4,Male,Self Study,80,65
15,5,7,5,Female,Coaching,85,70
16,6,6,5,Male,Group Study,88,72
17,7,7,6,Female,Self Study,90,75
18,8,8,3,Female,Self Study,92,80
19,4,6,5,Male,Self Study,85,60
20,3,5,6,Female,Coaching,78,69
21,2,6,7,Male,Self Study,70,52
22,5,8,4,Female,Group Study,85,68
24,7,6,6,Female,Coaching,90,75
25,8,7,4,Male,Group Study,92,80
31,7,7,6,Male,Self Study,90,76
47,1,5,8,Male,Self Study,65,45
48,9,8,2,Female,Coaching,96,88
49,10,7,1,Male,Self Study,98,92
50,1,4,9,Female,Group Study,60,40
51,9,9,2,Male,Self Study,97,90
52,10,8,1,Female,Coaching,99,94

In [20]:
from sklearn.preprocessing import LabelEncoder

In [21]:
r2 = df.Study_Method

In [22]:
le_study = LabelEncoder()

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
from sklearn.preprocessing import StandardScaler

In [25]:
from sklearn.linear_model import LinearRegression

In [26]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# ATTENDANCS

In [27]:
X = df[['Attendance']]
y = df['Final_Score']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Attendance")
MAE = mean_absolute_error(y_test, y_pred)
MSE = mean_squared_error(y_test, y_pred)
R2 = r2_score(y_test, y_pred)

print(f"MEAN ABSOLUTE ERROR :{MAE} ")
print(f"MEAN Squared ERROR :{MSE} ")
print(f"R2 Svore: {R2}")

Attendance
MEAN ABSOLUTE ERROR :1.6108825584103137
MEAN Squared ERROR :3.8761230103526882
R2 Svore: 0.9800158640423144

In [28]:
results = pd.DataFrame({
    "Actual": y_test,
    "Predicted": y_pred
})

print(results.head(10))

    Actual  Predicted
50      40  36.314109
15      70  70.205025
25      80  79.694481
17      75  76.983208
8       55  56.648658
9       65  66.138115
51      90  86.472664
31      76  76.983208
12      76  76.983208
0       55  56.648658